//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaKayıtOtomasyon_173301041
{
    using System;
    using System.Collections.Generic;
    
    public partial class Islem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Islem()
        {
            this.Sevk = new HashSet<Sevk>();
        }
    
        public int IslemId { get; set; }
        public string IslemAdi { get; set; }
        public string BirimFiyat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sevk> Sevk { get; set; }
    }
}
